// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaJ8XKdeawmEkthaT1Wn-LF18rJonGoBA',
    appId: '1:71130243032:web:d55f26e5ecd39eeefe5cad',
    messagingSenderId: '71130243032',
    projectId: 'firstcalendar-41000',
    authDomain: 'firstcalendar-41000.firebaseapp.com',
    storageBucket: 'firstcalendar-41000.appspot.com',
    measurementId: 'G-G45SKPFQVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxMkK0tH90dpl6v0EXBAG2qO6H4kxPZKs',
    appId: '1:71130243032:android:554308b9141e1582fe5cad',
    messagingSenderId: '71130243032',
    projectId: 'firstcalendar-41000',
    storageBucket: 'firstcalendar-41000.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8WSeIBK2zUpUcvFddTKjna05S2iR6LeY',
    appId: '1:71130243032:ios:96c2a4e76655140bfe5cad',
    messagingSenderId: '71130243032',
    projectId: 'firstcalendar-41000',
    storageBucket: 'firstcalendar-41000.appspot.com',
    iosBundleId: 'com.firstcalendar.medfare.firstcalendar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8WSeIBK2zUpUcvFddTKjna05S2iR6LeY',
    appId: '1:71130243032:ios:0dec6e2e2ef4517efe5cad',
    messagingSenderId: '71130243032',
    projectId: 'firstcalendar-41000',
    storageBucket: 'firstcalendar-41000.appspot.com',
    iosBundleId: 'com.firstcalendar.medfare.firstcalendar.RunnerTests',
  );
}
